apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo-ingressroute
  namespace: forgejo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: rpcloud-intermediate-ca1-issuer
    cert-manager.io/common-name: git.local
spec:
  ingressClassName: traefik
  rules:
    - host: git.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: forgejo-http
                port:
                  number: 3000
  tls:
    - hosts:
        - git.local
      secretName: forgejo-cert-secret
