apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-rpcloud
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rpcloud
  hostPath:
    path: /mnt/data/storage/
