---
- name: Basic software configuration
  hosts: master
  become: true
  tasks:
    - name: APT update
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install basic packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - nano
          - nfs-common
          - python3
          - python3-pip
        state: present

    - name: disable swap
      command: swapoff -a
