# Traefik Helm values configuration
deployment:
  replicas: 1
  nodeSelector:
    kubernetes.io/hostname: rpcloud

ports:
  web:
    port: 80
    nodePort: 30080
  websecure:
    port: 443
    nodePort: 30443
  traefik:
    port: 8080
    nodePort: 30808

service:
  type: NodePort

dashboard:
  enabled: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

logs:
  general:
    level: INFO
